AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-nodejs-rest

  Sample SAM Template for sam-nodejs-rest
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  LambdaFunctionList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: demo-app-list/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      #AutoPublishAlias: live
      #Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        EchoFind:
          Type: Api
          Properties:
            Path: /echo
            Method: get

  LambdaFunctionGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: demo-app-get/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      #AutoPublishAlias: live
      #Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        EchoFind:
          Type: Api
          Properties:
            Path: /echo/{id}
            Method: get

  LambdaFunctionEdit:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: demo-app-edit/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      #AutoPublishAlias: live
      #Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        EchoFind:
          Type: Api
          Properties:
            Path: /echo/{id}
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EchoApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/echo/"

