# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-nodejs-rest

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  LambdaFunctionFind:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: demo-app/
      Handler: find.lambdaHandler
      Runtime: nodejs14.x
      #AutoPublishAlias: live
      #Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        EchoFind:
          Type: Api
          Properties:
            Path: /echo/{id}
            Method: get

  LambdaFunctionEdit:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: demo-app-edit/
      Handler: find.lambdaHandler
      Runtime: nodejs14.x
      #AutoPublishAlias: live
      #Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        EchoFind:
          Type: Api
          Properties:
            Path: /echo/{id}
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EchoApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/echo/"
           